apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: namespace-cpu-usage-hourly
spec:
  reportingStart: "2019-01-01T00:00:00Z"
  generationQuery: "namespace-cpu-usage"
  schedule:
    period: "hourly"

