apiVersion: healthchecking.openshift.io/v1alpha1
kind: MachineHealthCheck
metadata:
  name: master
spec:
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-cluster: $clustername
      sigs.k8s.io/cluster-api-machine-role: master
      sigs.k8s.io/cluster-api-machine-type: master
