apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dhcp-daemon
  namespace: kube-system
  labels:
    app: multus
    tier: node
spec:
  selector:
    matchLabels:
      app: multus
      tier: node
  template:
    metadata:
      labels:
        app: multus
        tier: node
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image: openshift/ose-container-networking-plugins-supported:v4.0
        name: dhcp-daemon
        command: ["/bin/bash"]
        args: ["-c", "rm -f /run/cni/dhcp.sock && /usr/src/plugins/bin/dhcp daemon"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/cni/
          name: dhcp-sock
      serviceAccount: multus
      serviceAccountName: multus
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /run/cni/
        name: dhcp-sock
