apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "openshift.com/nfs"
    fstype: "nfs"
    options:
      server: #SERVER#
      share: "/nfs"
